style: is-light
height: is-medium
items:
  - title: General Consultation
    icon: fa-stethoscope
    description: >
      Klinik Kenanga is the primary point of contact for patients
      seeking general healthcare services. 

  - title: Minor Surgery
    icon: fa-bandage
    description: >
      We perform minor surgical procedures under local anesthesia in an outpatient setting.

  - title: Home Visits.
    icon: fa-house-medical-circle-check
    description: >
      We provide the convenience of home visits for patients who are unable to visit the clinic. 

  - title: Palliative Care Services
    icon: fa-bed-pulse
    description: >
      We offer palliative care services, focusing on enhancing the quality of life for individuals with serious illnesses, often in the comfort of their own homes.
      
  - title: Health Screening
    icon: fa-droplet
    description: >
      These assessments aim to detect potential health issues early, enabling timely intervention and preventive measures.

  - title: Wound Care
    icon: fa-suitcase-medical
    icon_brand: true
    description: >
      We support your wound healing journey with personalized attention, advanced wound care techniques and modern dressing.

  - title: Preventive Vaccination
    icon: fa-syringe
    icon_brand: true
    description: >
      We offer preventive vaccinations for both adults and children, helping to protect individuals 
      from various infectious diseases.